[2024-08-28T19:35:45.043+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_gold_ts.process_gold_ts_and_metrics manual__2024-08-28T19:35:02.662054+00:00 [queued]>
[2024-08-28T19:35:45.050+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_gold_ts.process_gold_ts_and_metrics manual__2024-08-28T19:35:02.662054+00:00 [queued]>
[2024-08-28T19:35:45.050+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-08-28T19:35:45.050+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-08-28T19:35:45.050+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-08-28T19:35:45.060+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): process_gold_ts_and_metrics> on 2024-08-28 19:35:02.662054+00:00
[2024-08-28T19:35:45.067+0000] {standard_task_runner.py:55} INFO - Started process 1670 to run task
[2024-08-28T19:35:45.069+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_gold_ts', 'process_gold_ts_and_metrics', 'manual__2024-08-28T19:35:02.662054+00:00', '--job-id', '12477', '--raw', '--subdir', 'DAGS_FOLDER/dag_ts_inmet.py', '--cfg-path', '/tmp/tmp4zmdmt09']
[2024-08-28T19:35:45.070+0000] {standard_task_runner.py:83} INFO - Job 12477: Subtask process_gold_ts_and_metrics
[2024-08-28T19:35:45.112+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_gold_ts.process_gold_ts_and_metrics manual__2024-08-28T19:35:02.662054+00:00 [running]> on host 50af263b1053
[2024-08-28T19:35:45.166+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_gold_ts
AIRFLOW_CTX_TASK_ID=process_gold_ts_and_metrics
AIRFLOW_CTX_EXECUTION_DATE=2024-08-28T19:35:02.662054+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-08-28T19:35:02.662054+00:00
[2024-08-28T19:35:47.597+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/pyspark/context.py:317: FutureWarning: Python 3.7 support is deprecated in Spark 3.4.
  warnings.warn("Python 3.7 support is deprecated in Spark 3.4.", FutureWarning)

[2024-08-28T19:35:52.772+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'DATA'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_ts_inmet.py", line 36, in run_gold_ts_and_calculate_metrics
    pdf, predictions_df = gold_ts.ts_gold(spark)
  File "/opt/airflow/plugins/gold_ts_plugin.py", line 14, in wrapper
    resultado = metodo(*args, **kwargs)
  File "/opt/airflow/plugins/gold_ts_plugin.py", line 102, in ts_gold
    predictions_df['DATA'] = pd.to_datetime(predictions_df['DATA'], format='%Y-%m-%d')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'DATA'
[2024-08-28T19:35:52.781+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=dag_gold_ts, task_id=process_gold_ts_and_metrics, execution_date=20240828T193502, start_date=20240828T193545, end_date=20240828T193552
[2024-08-28T19:35:52.791+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 12477 for task process_gold_ts_and_metrics ('DATA'; 1670)
[2024-08-28T19:35:52.823+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-08-28T19:35:52.847+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
