[2024-08-06T13:20:15.939+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_inmet.download_data manual__2024-08-06T13:19:25.906694+00:00 [queued]>
[2024-08-06T13:20:15.947+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_inmet.download_data manual__2024-08-06T13:19:25.906694+00:00 [queued]>
[2024-08-06T13:20:15.947+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-08-06T13:20:15.947+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-08-06T13:20:15.947+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-08-06T13:20:15.957+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): download_data> on 2024-08-06 13:19:25.906694+00:00
[2024-08-06T13:20:15.962+0000] {standard_task_runner.py:55} INFO - Started process 1301 to run task
[2024-08-06T13:20:15.963+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_inmet', 'download_data', 'manual__2024-08-06T13:19:25.906694+00:00', '--job-id', '4249', '--raw', '--subdir', 'DAGS_FOLDER/dag_inmet.py', '--cfg-path', '/tmp/tmpmvlez8cp']
[2024-08-06T13:20:15.965+0000] {standard_task_runner.py:83} INFO - Job 4249: Subtask download_data
[2024-08-06T13:20:16.005+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_inmet.download_data manual__2024-08-06T13:19:25.906694+00:00 [running]> on host 0279e29945ad
[2024-08-06T13:20:16.058+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_inmet
AIRFLOW_CTX_TASK_ID=download_data
AIRFLOW_CTX_EXECUTION_DATE=2024-08-06T13:19:25.906694+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-08-06T13:19:25.906694+00:00
[2024-08-06T13:20:41.433+0000] {logging_mixin.py:137} INFO - Erro ao acessar a página ou link não encontrado: 403
[2024-08-06T13:20:41.434+0000] {logging_mixin.py:137} INFO - Tempo de execução de download_data: 25.3755 segundos
[2024-08-06T13:20:41.436+0000] {dag_inmet.py:56} ERROR - Erro ao baixar e salvar o arquivo: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
[2024-08-06T13:20:41.437+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_inmet.py", line 53, in task_download_data
    filename = bronze.download_and_save_file(url)
  File "/opt/airflow/plugins/bronze_plugin.py", line 12, in wrapper
    resultado = metodo(*args, **kwargs)
  File "/opt/airflow/plugins/bronze_plugin.py", line 60, in download_and_save_file
    response = requests.get(url, headers=headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/sessions.py", line 496, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 440, in prepare_url
    f"Invalid URL {url!r}: No scheme supplied. "
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
[2024-08-06T13:20:41.469+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=dag_inmet, task_id=download_data, execution_date=20240806T131925, start_date=20240806T132015, end_date=20240806T132041
[2024-08-06T13:20:41.500+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4249 for task download_data (Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?; 1301)
[2024-08-06T13:20:41.518+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-08-06T13:20:41.543+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
