[2024-08-29T15:29:07.726+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_gold_ts.wait_for_dag_inmet scheduled__2024-07-29T15:28:00+00:00 [queued]>
[2024-08-29T15:29:07.736+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_gold_ts.wait_for_dag_inmet scheduled__2024-07-29T15:28:00+00:00 [queued]>
[2024-08-29T15:29:07.736+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-08-29T15:29:07.736+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-08-29T15:29:07.736+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-08-29T15:29:07.748+0000] {taskinstance.py:1300} INFO - Executing <Task(ExternalTaskSensor): wait_for_dag_inmet> on 2024-07-29 15:28:00+00:00
[2024-08-29T15:29:07.757+0000] {standard_task_runner.py:55} INFO - Started process 508 to run task
[2024-08-29T15:29:07.759+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_gold_ts', 'wait_for_dag_inmet', 'scheduled__2024-07-29T15:28:00+00:00', '--job-id', '13227', '--raw', '--subdir', 'DAGS_FOLDER/dag_ts_inmet.py', '--cfg-path', '/tmp/tmpjprpgzj8']
[2024-08-29T15:29:07.761+0000] {standard_task_runner.py:83} INFO - Job 13227: Subtask wait_for_dag_inmet
[2024-08-29T15:29:07.817+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_gold_ts.wait_for_dag_inmet scheduled__2024-07-29T15:28:00+00:00 [running]> on host d813130246e9
[2024-08-29T15:29:07.887+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_gold_ts
AIRFLOW_CTX_TASK_ID=wait_for_dag_inmet
AIRFLOW_CTX_EXECUTION_DATE=2024-07-29T15:28:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-07-29T15:28:00+00:00
[2024-08-29T15:39:08.521+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 215, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 600.6326162709956 seconds exceeds the specified timeout of 600.
[2024-08-29T15:39:08.526+0000] {taskinstance.py:1323} INFO - Immediate failure requested. Marking task as FAILED. dag_id=dag_gold_ts, task_id=wait_for_dag_inmet, execution_date=20240729T152800, start_date=20240829T152907, end_date=20240829T153908
[2024-08-29T15:39:08.542+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 13227 for task wait_for_dag_inmet (Sensor has timed out; run duration of 600.6326162709956 seconds exceeds the specified timeout of 600.; 508)
[2024-08-29T15:39:08.561+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-08-29T15:39:08.583+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
