[2024-08-22T15:05:51.643+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: sarima_forecast_dag.run_sarima_forecast manual__2024-08-22T15:05:44.536296+00:00 [queued]>
[2024-08-22T15:05:51.654+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: sarima_forecast_dag.run_sarima_forecast manual__2024-08-22T15:05:44.536296+00:00 [queued]>
[2024-08-22T15:05:51.654+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-08-22T15:05:51.655+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-08-22T15:05:51.655+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-08-22T15:05:51.667+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): run_sarima_forecast> on 2024-08-22 15:05:44.536296+00:00
[2024-08-22T15:05:51.673+0000] {standard_task_runner.py:55} INFO - Started process 2288 to run task
[2024-08-22T15:05:51.675+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sarima_forecast_dag', 'run_sarima_forecast', 'manual__2024-08-22T15:05:44.536296+00:00', '--job-id', '10792', '--raw', '--subdir', 'DAGS_FOLDER/dag_forecast_ts_rainfall.py', '--cfg-path', '/tmp/tmp_zyl427d']
[2024-08-22T15:05:51.676+0000] {standard_task_runner.py:83} INFO - Job 10792: Subtask run_sarima_forecast
[2024-08-22T15:05:51.717+0000] {task_command.py:388} INFO - Running <TaskInstance: sarima_forecast_dag.run_sarima_forecast manual__2024-08-22T15:05:44.536296+00:00 [running]> on host f64a695c5a62
[2024-08-22T15:05:51.770+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sarima_forecast_dag
AIRFLOW_CTX_TASK_ID=run_sarima_forecast
AIRFLOW_CTX_EXECUTION_DATE=2024-08-22T15:05:44.536296+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-08-22T15:05:44.536296+00:00
[2024-08-22T15:05:52.008+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/statsmodels/tsa/statespace/sarimax.py:868: UserWarning: Too few observations to estimate starting parameters for seasonal ARMA. All parameters except for variances will be set to zeros.
  ' zeros.' % warning_description)

[2024-08-22T15:05:52.057+0000] {python.py:177} INFO - Done. Returned value was:                  Date    Forecast
2024-01-01 2024-07-01  285.536807
[2024-08-22T15:05:52.086+0000] {xcom.py:635} ERROR - Object of type DataFrame is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2024-08-22T15:05:52.089+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2297, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 170, in default
    return super().default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2024-08-22T15:05:52.104+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=sarima_forecast_dag, task_id=run_sarima_forecast, execution_date=20240822T150544, start_date=20240822T150551, end_date=20240822T150552
[2024-08-22T15:05:52.129+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 10792 for task run_sarima_forecast (Object of type DataFrame is not JSON serializable; 2288)
[2024-08-22T15:05:52.167+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-08-22T15:05:52.180+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
