[2024-06-28T13:34:55.004+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdag3.tsk1 manual__2024-06-28T13:34:53.773106+00:00 [queued]>
[2024-06-28T13:34:55.011+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdag3.tsk1 manual__2024-06-28T13:34:53.773106+00:00 [queued]>
[2024-06-28T13:34:55.012+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-06-28T13:34:55.012+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-06-28T13:34:55.012+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-06-28T13:34:55.021+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk1> on 2024-06-28 13:34:53.773106+00:00
[2024-06-28T13:34:55.026+0000] {standard_task_runner.py:55} INFO - Started process 101 to run task
[2024-06-28T13:34:55.028+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'triggerdag3', 'tsk1', 'manual__2024-06-28T13:34:53.773106+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/triggerdag3.py', '--cfg-path', '/tmp/tmpp5cpav8r']
[2024-06-28T13:34:55.028+0000] {standard_task_runner.py:83} INFO - Job 164: Subtask tsk1
[2024-06-28T13:34:55.066+0000] {task_command.py:388} INFO - Running <TaskInstance: triggerdag3.tsk1 manual__2024-06-28T13:34:53.773106+00:00 [running]> on host df354ccffee8
[2024-06-28T13:34:55.113+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=triggerdag3
AIRFLOW_CTX_TASK_ID=tsk1
AIRFLOW_CTX_EXECUTION_DATE=2024-06-28T13:34:53.773106+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-06-28T13:34:53.773106+00:00
[2024-06-28T13:34:55.114+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-06-28T13:34:55.114+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-06-28T13:34:55.125+0000] {subprocess.py:86} INFO - Output:
[2024-06-28T13:34:55.127+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-06-28T13:34:55.134+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-06-28T13:34:55.136+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=triggerdag3, task_id=tsk1, execution_date=20240628T133453, start_date=20240628T133455, end_date=20240628T133455
[2024-06-28T13:34:55.144+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 164 for task tsk1 (Bash command failed. The command returned a non-zero exit code 1.; 101)
[2024-06-28T13:34:55.160+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-06-28T13:34:55.218+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
