[2024-08-28T14:43:13.829+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: sarima_forecast_dag.run_sarima_forecast manual__2024-08-28T14:42:58.827126+00:00 [queued]>
[2024-08-28T14:43:13.836+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: sarima_forecast_dag.run_sarima_forecast manual__2024-08-28T14:42:58.827126+00:00 [queued]>
[2024-08-28T14:43:13.836+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-08-28T14:43:13.836+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-08-28T14:43:13.836+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-08-28T14:43:13.846+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): run_sarima_forecast> on 2024-08-28 14:42:58.827126+00:00
[2024-08-28T14:43:13.853+0000] {standard_task_runner.py:55} INFO - Started process 15801 to run task
[2024-08-28T14:43:13.855+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sarima_forecast_dag', 'run_sarima_forecast', 'manual__2024-08-28T14:42:58.827126+00:00', '--job-id', '12123', '--raw', '--subdir', 'DAGS_FOLDER/dag_forecast_ts_rainfall.py', '--cfg-path', '/tmp/tmpum2_0wh4']
[2024-08-28T14:43:13.856+0000] {standard_task_runner.py:83} INFO - Job 12123: Subtask run_sarima_forecast
[2024-08-28T14:43:13.898+0000] {task_command.py:388} INFO - Running <TaskInstance: sarima_forecast_dag.run_sarima_forecast manual__2024-08-28T14:42:58.827126+00:00 [running]> on host 4958d38180c6
[2024-08-28T14:43:13.948+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sarima_forecast_dag
AIRFLOW_CTX_TASK_ID=run_sarima_forecast
AIRFLOW_CTX_EXECUTION_DATE=2024-08-28T14:42:58.827126+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-08-28T14:42:58.827126+00:00
[2024-08-28T14:43:14.392+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/statsmodels/tsa/statespace/sarimax.py:868: UserWarning: Too few observations to estimate starting parameters for seasonal ARMA. All parameters except for variances will be set to zeros.
  ' zeros.' % warning_description)

[2024-08-28T14:43:14.537+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_forecast_ts_rainfall.py", line 29, in run_sarima_forecast
    previsoes_df.to_csv('/home/kleuber/Documentos/projeto_airflow/data/gold/rainfall_ts/artifacts/forecast_output.csv', index=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/home/kleuber/Documentos/projeto_airflow/data/gold/rainfall_ts/artifacts/forecast_output.csv'
[2024-08-28T14:43:14.560+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=sarima_forecast_dag, task_id=run_sarima_forecast, execution_date=20240828T144258, start_date=20240828T144313, end_date=20240828T144314
[2024-08-28T14:43:14.584+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 12123 for task run_sarima_forecast ([Errno 2] No such file or directory: '/home/kleuber/Documentos/projeto_airflow/data/gold/rainfall_ts/artifacts/forecast_output.csv'; 15801)
[2024-08-28T14:43:14.628+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-08-28T14:43:14.640+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
