[2024-08-22T16:10:48.692+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: sarima_forecast_dag.run_sarima_forecast manual__2024-08-22T16:10:20.566343+00:00 [queued]>
[2024-08-22T16:10:48.699+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: sarima_forecast_dag.run_sarima_forecast manual__2024-08-22T16:10:20.566343+00:00 [queued]>
[2024-08-22T16:10:48.699+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-08-22T16:10:48.699+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-08-22T16:10:48.699+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-08-22T16:10:48.709+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): run_sarima_forecast> on 2024-08-22 16:10:20.566343+00:00
[2024-08-22T16:10:48.715+0000] {standard_task_runner.py:55} INFO - Started process 2383 to run task
[2024-08-22T16:10:48.717+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sarima_forecast_dag', 'run_sarima_forecast', 'manual__2024-08-22T16:10:20.566343+00:00', '--job-id', '10894', '--raw', '--subdir', 'DAGS_FOLDER/dag_forecast_ts_rainfall.py', '--cfg-path', '/tmp/tmpu2fzz1kd']
[2024-08-22T16:10:48.719+0000] {standard_task_runner.py:83} INFO - Job 10894: Subtask run_sarima_forecast
[2024-08-22T16:10:48.761+0000] {task_command.py:388} INFO - Running <TaskInstance: sarima_forecast_dag.run_sarima_forecast manual__2024-08-22T16:10:20.566343+00:00 [running]> on host 8908f8dde14f
[2024-08-22T16:10:48.810+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sarima_forecast_dag
AIRFLOW_CTX_TASK_ID=run_sarima_forecast
AIRFLOW_CTX_EXECUTION_DATE=2024-08-22T16:10:20.566343+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-08-22T16:10:20.566343+00:00
[2024-08-22T16:10:48.811+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_forecast_ts_rainfall.py", line 15, in run_sarima_forecast
    sarima_plugin.load_model()
  File "/opt/airflow/plugins/forecast_ts_rainfall_plugin.py", line 13, in load_model
    self.sarima_model = load(self.model_path)
  File "/home/airflow/.local/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 650, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/data/gold/artifacts/sarima_model_v_062024.joblib'
[2024-08-22T16:10:48.817+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=sarima_forecast_dag, task_id=run_sarima_forecast, execution_date=20240822T161020, start_date=20240822T161048, end_date=20240822T161048
[2024-08-22T16:10:48.825+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 10894 for task run_sarima_forecast ([Errno 2] No such file or directory: '/home/airflow/data/gold/artifacts/sarima_model_v_062024.joblib'; 2383)
[2024-08-22T16:10:48.849+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-08-22T16:10:48.864+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
