[2024-08-06T20:23:34.693+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_inmet.send_email_results manual__2024-08-06T19:56:23.962703+00:00 [queued]>
[2024-08-06T20:23:34.707+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: dag_inmet.send_email_results manual__2024-08-06T19:56:23.962703+00:00 [queued]>
[2024-08-06T20:23:34.707+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-08-06T20:23:34.707+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-08-06T20:23:34.707+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-08-06T20:23:34.723+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): send_email_results> on 2024-08-06 19:56:23.962703+00:00
[2024-08-06T20:23:34.734+0000] {standard_task_runner.py:55} INFO - Started process 15484 to run task
[2024-08-06T20:23:34.736+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_inmet', 'send_email_results', 'manual__2024-08-06T19:56:23.962703+00:00', '--job-id', '4767', '--raw', '--subdir', 'DAGS_FOLDER/dag_inmet.py', '--cfg-path', '/tmp/tmpdm6tadvn']
[2024-08-06T20:23:34.738+0000] {standard_task_runner.py:83} INFO - Job 4767: Subtask send_email_results
[2024-08-06T20:23:34.797+0000] {task_command.py:388} INFO - Running <TaskInstance: dag_inmet.send_email_results manual__2024-08-06T19:56:23.962703+00:00 [running]> on host 9064bbdb1ace
[2024-08-06T20:23:34.885+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_inmet
AIRFLOW_CTX_TASK_ID=send_email_results
AIRFLOW_CTX_EXECUTION_DATE=2024-08-06T19:56:23.962703+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-08-06T19:56:23.962703+00:00
[2024-08-06T20:23:34.985+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_inmet.py", line 178, in send_email
    dag_duration = (dag_end - dag_start).total_seconds()
TypeError: can't subtract offset-naive and offset-aware datetimes
[2024-08-06T20:23:34.992+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=dag_inmet, task_id=send_email_results, execution_date=20240806T195623, start_date=20240806T202334, end_date=20240806T202334
[2024-08-06T20:23:35.006+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4767 for task send_email_results (can't subtract offset-naive and offset-aware datetimes; 15484)
[2024-08-06T20:23:35.028+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-08-06T20:23:35.043+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
